### ISSUE TITLE
BUG: Newest version seems to be "broken" for neovim; missing basics-language-server.cmd

### ISSUE THREAD

**Issue by GitMurf** [antonk52/basics-language-server#10]
I am not completely sure how it is all supposed to work, but I just know I tried updating and it gave me errors and then I reverted back to version 1.0.2 and it worked fine again.

I then did a comparison to the package structure and in the old 1.0.2 (working) it had `node_modules/.bin/basics-language-server*` (.cmd and .ps1 version as well). But in the updated version all that was there are the 3 `installServerIntoExtension*` files.

Here is the good WORKING 1.0.2 (these 3 files are completely missing in 1.1.1):

![image](https://github.com/user-attachments/assets/4c022142-4ebe-4d5d-b46a-8a61bc889eca)

**Comment by GitMurf** [comment]
It seems based off the package.json it is supposed to be build to `dist/cli.js` and `dist/connection.js` ...

![image](https://github.com/user-attachments/assets/c35d9fed-f44c-4889-8dc3-8dbf6dcd7c99)

But the actual install has `src` in the path:

![image](https://github.com/user-attachments/assets/8754f6ad-e8fe-4e45-a1db-6acdb2189998)

**Comment by antonk52** [comment]
Sorry for only noticing the issue just now.

I've fixed the issue and released [v1.1.2](https://github.com/antonk52/basics-language-server/releases/tag/v1.1.2)

The issue should be fixed now. Still no idea why this happened as neither typescript version nor tsconfig.json file did not change since the initial commit.
